
 
 const mascotas = [
    {
        id: 001,
        nombre: "Coco",
        tipo: "perro",
        edad: "7 años",
        tamanio: "mediano",
        descripcion: "Coco es un perro de tamaño mediano de 7 años de edad, se lleva muy bien con otros animales.",
        imagePath: "/imagenes/1.jpg",
        modal: "s1",
        vacunas: "Si",
        castrado: "Si",
    },
    {
        id: 002,
        nombre: "Dana",
        tipo: "perro",
        edad: "1 año",
        tamanio: "mediano",
        descripcion: "Dana es un perro de tamaño mediano que se lleva muy bien con otros animales.",
        imagePath: "/imagenes/2.jpg",
        modal: "s2",
        vacunas: "Si",
        castrado: "No",
    },
    {
        id: 003,
        nombre: "Pepe",
        tipo: "perro",
        edad: "2 años",
        tamanio: "mediano",
        descripcion: "Pepe es un perro muy alegre y compañero, no se lleva bien con gatos.",
        imagePath: "/imagenes/3.jpg",
        modal: "s3",
        vacunas: "Si",
        castrado: "Si",
    },
    {
        id: 004,
        nombre: "Teo",
        tipo: "perro",
        edad: "1 año",
        tamanio: "chico",
        descripcion: "Teo es muy afectuoso, aunque aveces necesita su espacio.",
        imagePath: "/imagenes/7.jpg",
        modal: "s4",
        vacunas: "Si",
        castrado: "No",
    },
    {
        id: 005,
        nombre: "Tomi",
        tipo: "perro",
        edad: "3 años",
        tamanio: "mediano",
        descripcion: "Tomi es un perro muy alegre y guardian.",
        imagePath: "/imagenes/4.jpg",
        modal: "s5",
        vacunas: "Si",
        castrado: "Si",
    },
    {
        id: 006,
        nombre: "Felix",
        tipo: "Gato",
        edad: "2 años",
        tamanio: "chico",
        descripcion: "Felix es un gato my amigable y tranquilo, se lleva bien con otros gatos.",
        imagePath: "/imagenes/8.jpg",
        modal: "s6",
        vacunas: "Si",
        castrado: "Si",
    },
    {
        id: 007,
        nombre: "Felipe",
        tipo: "perro",
        edad: "5 años",
        tamanio: "mediano",
        descripcion: "Felipe es muy guardian y cariñoso, no se lleva bien con otros animales.",
        imagePath: "/imagenes/5.jpg",
        modal: "s7",
        vacunas: "Si",
        castrado: "Si",
    },
    {
        id: 008,
        nombre: "Comando",
        tipo: "perro",
        edad: "4 años",
        tamanio: "mediano",
        descripcion: "Comando es un perro de tamaño mediano de 4 años de edad, se lleva muy bien con otros animales.",
        imagePath: "/imagenes/6.jpg",
        modal: "s8",
        vacunas: "Si",
        castrado: "Si",
    },
    {
        id: 009,
        nombre: "Tito",
        tipo: "Gato",
        edad: "3 meses",
        tamanio: "chico",
        descripcion: "Tito es muy afectuoso y esta buscando una nueva familia.",
        imagePath: "/imagenes/9.jpg",
        modal: "s9",
        vacunas: "Si",
        castrado: "Si",
    },
]